---
- name: User with homedir and shell
  hosts: webservers
  become: yes
  tasks:

    - name: Add devops user and give shell + home dir
      user:
        name: devops
        shell: /bin/bash
        create_home: yes
